name: Testing Push event
on: push
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

  test:
    runs-on: ubuntu-latest
    steps: 
      - name: Run test
        run: echo "This is a test job"

