name: Test POC for Github Action
on: push
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v4
   - name: Priniting an echo statement
     run: echo Testing, the Github actions !!
